version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    command: --log-bin-trust-function-creators=1 
     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "5050:80"
    depends_on:
      - mysql
    restart: unless-stopped


volumes:
  mysql_data:

# version: '3.8'

# services:
#   api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     depends_on:
#       - mysql
#     environment:
#       - DB_HOST=localhost
#       - DB_PORT=3306
#       - DB_USER=myuser
#       - DB_PASSWORD=mypassword
#       - DB_NAME=mydatabase

#   mysql:
#     image: mysql:8.0
#     container_name: mysql
#     environment:
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#       MYSQL_ROOT_PASSWORD: rootpassword
#     volumes:
#       - mysql_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     restart: unless-stopped
#     command: --log-bin-trust-function-creators=1 
     
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     container_name: phpmyadmin
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: rootpassword
#     ports:
#       - "5050:80"
#     depends_on:
#       - mysql
#     restart: unless-stopped

# volumes:
#   mysql_data:
